AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 10

